TEXT = "text"
PRICE = "price"
USERS = "users"
POLLS = "polls"
CLICKS = "clicks"
OPTIONS = "options"
DEBT_SUM = "debt_sum"
VOTERS_COUNT = "voters_count"

POLL_ID = "poll_id"
CHAT_ID = "chat_id"
USER_ID = "user_id"
RECEIPT_ID = "receipt_id"
MESSAGE_ID = "message_id"
OPTIONS_IDS = "option_ids"
DIALOG_STATE_ID = "dialog_state_id"

TOTAL_VOTERS_COUNT = "total_voters_count"
ACCESS_TIMESTAMP = "access_timestamp"
IS_RECEIPT_CLOSED = "is_receipt_closed"
