USERS = "users"
DEBT_SUM = "debt_sum"
RAW_ITEMS = "raw_items"
CLEAN_ITEMS = "clean_items"
VOTERS_COUNT = "voters_count"
OPTIONS_MARKUP = "options_markup"
RECEIPT_MARKUP = "receipt_markup"

CHAT_ID = "chat_id"
USER_ID = "user_id"
RECEIPT_ID = "receipt_id"
DIALOG_STATE_ID = "dialog_state_id"

TOTAL_VOTERS_COUNT = "total_voters_count"
ACCESS_TIMESTAMP = "access_timestamp"
IS_RECEIPT_CLOSED = "is_receipt_closed"
