---
loggers:
  behavior_logger:
    handlers:
    - console_handler
    - file_handler
    propagate: false
    level: DEBUG
version: 1

root:
  handlers:
  - console_handler
  level: INFO

handlers:
  console_handler:
    formatter: console_simple_formatter
    class: logging.StreamHandler
    stream: ext://sys.stdout
  file_handler:
    formatter: console_simple_formatter
    backupCount: 30
    encoding: utf-8
    filename: "/tmp/system.log"
    class: logging.handlers.RotatingFileHandler
    maxBytes: 15728640

formatters:
  console_simple_formatter:
    format: "[%(levelname)s] %(name)s %(asctime)s %(module)s: %(message)s"